global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway-aggregated'
    metrics_path: '/actuator/metrics/all'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
